version: '2'
services:

  presto-master:
    volumes:
      - ../../../conf/presto/etc/environment-specific-catalogs/singlenode-kerberos-hive-impersonation/hive.properties:/docker/presto-product-tests/conf/presto/etc/catalog/hive.properties
      - ../../../conf/presto/etc/environment-specific-catalogs/singlenode-kerberos-hive-impersonation/iceberg.properties:/docker/presto-product-tests/conf/presto/etc/catalog/iceberg.properties
